### ISSUE TITLE
my-mybatis

### ISSUE THREAD

**Issue by ztg-zlu** [cdgeass/my-mybatis-plugin#13]
大佬，现在，插件，my-mybatis搜索不到了，要搜my mybatis，还有个，原来可以，直接复制到剪贴板的，现在，怎么，只有格式化，出来还要点击复制，还出来复制成功窗口，好麻烦

**Comment by cdgeass** [comment]
2.1.0加上了直接复制，但是因为美化是用的 IDEA 的功能所以直接复制出来的是没有美化过的，2.1.0 因为 IDEA 的 api 变更所以需要 IDEA 更新到22.1，22.1还没正式发布，如果你不打算更新那我在21.3上加个版本
