### ISSUE TITLE
empty param will not be replaced

### ISSUE THREAD

**Issue by M1NGc** [cdgeass/my-mybatis-plugin#4]
![image](https://user-images.githubusercontent.com/26264126/82981938-afacf700-a01f-11ea-82b0-22a2865a3942.png)

**Comment by M1NGc** [comment]
empty param will occured wrong replace ![image](https://user-images.githubusercontent.com/26264126/82982080-f7338300-a01f-11ea-91ef-927797b2ae44.png)

**Comment by cdgeass** [comment]
1.1.4的已经修改了，发布审核中，也可以手动更新
