### ISSUE TITLE
复制sql语句存在Bug

### ISSUE THREAD

**Issue by caidingnu** [cdgeass/my-mybatis-plugin#6]
like查询的时候只能不能复制左边的%

执行的Sql：
 SELECT role_id,
role_name,
user_id,
create_time,
update_time 
FROM role
 WHERE (role_id = 'arameters: 70debe013c363d52e48c56114e17a8b9' AND role_name LIKE '%ad8b%')

插件复制的sql：
SELECT role_id
    ,role_name
    ,user_id
    ,create_time
    ,update_time
FROM role
WHERE (role_id = '70debe013c363d52e48c56114e17a8b9' AND role_name LIKE 'ad8b%');

**Comment by cdgeass** [comment]
可以提供下原log吗

**Comment by caidingnu** [comment]
2021-01-04 11:57:35.722 [http-nio-51-exec-1] DEBUG c.c.c.mapper.RoleMapper.selectList -==>  Preparing: SELECT role_id,role_name,user_id,create_time,update_time FROM role WHERE (role_id = ? OR (role_name LIKE ?)) 
2021-01-04 11:57:35.758 [http-nio-51-exec-1] DEBUG c.c.c.mapper.RoleMapper.selectList -==> Parameters: 70debe013c363d52e48c56114e17a8b9(String), %757f44bf2f13%(String) 
2021-01-04 11:57:35.841 [http-nio-51-exec-1] DEBUG c.c.c.mapper.RoleMapper.selectList -<==      Total: 1

**Comment by caidingnu** [comment]
环境：idea 2020.3
          持久层：MybatisPlus
         springboot：2.3.0.RELEASE

**Comment by cdgeass** [comment]
已经在1.2.9修复，感谢反馈！

**Comment by caidingnu** [comment]
这个插件后期是收费还是免费？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cdgeass/my-mybatis-plugin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月5日(星期二) 下午5:29
收件人:&nbsp;"cdgeass/my-mybatis-plugin"<my-mybatis-plugin@noreply.github.com&gt;;
抄送:&nbsp;"蔡定努"<903321643@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cdgeass/my-mybatis-plugin] 复制sql语句存在Bug (#6)





 
已经在1.2.9修复，感谢反馈！

**Comment by cdgeass** [comment]
免费的~

**Comment by caidingnu** [comment]
老铁，1.2.9  发布一个呗

**Comment by cdgeass** [comment]
发布了，插件版本发布需要等待审核的~

**Comment by caidingnu** [comment]
膜拜大佬 ，强
